### ISSUE TITLE
How to send messsage to more than one people ?

### ISSUE THREAD

**Issue by holograman01** [fomalhaut88/interpals-api#7]
Hi, first of all i want to thank you for such a program. it works perfectly. I want to ask that how can i message multiple messages by using this program? 

i tried this command line but not worked

> uid = api.get_uid('user1,user2,user3')

i got this error

> Traceback (most recent call last):
  File "C:\Users\Ali\Desktop\interpals-api-master\interpals.py", line 22, in <module>
    uid = api.get_uid('Minzz.00,captainholo')
  File "C:\Users\Ali\Desktop\interpals-api-master\interpals_api\api.py", line 91, in get_uid
    profile_info = self.profile(user)
  File "C:\Users\Ali\Desktop\interpals-api-master\interpals_api\api.py", line 52, in profile
    data = parser.parse(response.text)
  File "C:\Users\Ali\Desktop\interpals-api-master\interpals_api\parsers\profile_parser.py", line 10, in parse
    data.update(self._extract_name_age_sex(soup))
  File "C:\Users\Ali\Desktop\interpals-api-master\interpals_api\parsers\profile_parser.py", line 24, in _extract_name_age_sex
    sex = profile_box.find('img')['src'].split('/')[-1][:-7]
AttributeError: 'NoneType' object has no attribute 'find'

thankks for help

**Comment by fomalhaut88** [comment]
Hi. According to the way Interpals engine works, each user has his own user-id that is unique. This is the value that api.get_uid returns. So you cannot get one user-id for multiple users with one call. We need user-id in order to create a chat (by the method api.get_thread_id that returns thread-id that is an identifier of the chat) and to send your message to the created chat (by api.chat_send that accepts thread-id as argument). As far as you want to send a message to different users, you will have to send it to different chats that have different thread-id, that you have to extract separately. So if you want to send a message to different users, just do it in the loop.

**Comment by holograman01** [comment]
I'm asking for be sure. So I have to try one by one for each username, right?

**Comment by fomalhaut88** [comment]
Yes.
